### ISSUE TITLE
Combat events for trial mechanics 

### ISSUE THREAD

**Issue by oranje-elf** [Solinur/CombatMetrics#1]
I would like to take the log generated by the combat metrics and make an advice to dds where their dps is lost (comparing to other people or based on the mechanics of the trial, etc).

So far I was able to decode the log, and to turn it into a sequence of events (combat, event, power, message, etc) that I can look through. However, I do not see any events with abilities representing the mechanics of the trial. For example, there is no event with id 98535 (which corresponds to asylum.olms_storm_the_heavens according to the raid notifier addon). 

Would it be possible to add those events to the combat metrics log as well? They are not happening that often, I do not think that the log will become that much bigger because of these extra events (you already generate about 120k events for a 30min fight in a trial, those extra events representing mechanics will only add a fraction of those) but it will be extremely useful to see how your dps is influenced by the mechanics of the trial.

**Comment by Solinur** [comment]
Sorry, I only saw this now. Like I wrote on ESOUI, this requires thatsomeone creates and matains a list of Id's or mechanics in question, something that goes beyond what I want to invest on that end. If someone provides that data, I will implement this into Combat Metrics.
