### ISSUE TITLE
Question about saved fight data

### ISSUE THREAD

**Issue by kmattix** [Solinur/CombatMetrics#10]
Hey there, Solinur. I'm about to start development on a discord bot that will automatically assign parse tags in Discord and I'm looking to use CMX for this. I was wondering where the fight data is stored for fights? I plan on using whatever data is saved to do this. Thanks!

**Comment by Solinur** [comment]
Sorry, somehow I forgot about your inquiry.
In case this your question is still relevant: Fight data is saved in "SavedVariables\CombatMetricsFightData.lua".
