### ISSUE TITLE
User ID too long

### ISSUE THREAD

**Issue by laurie-boissay** [Solinur/CombatMetrics#11]
Hello,

First to all, thank you for this wonderfull addon that we use in my guild !

Today someone shared his DPS on our discord but his user ID is 20 signs long. So I can't see the time code.
![Capture_decran_2022-03-19_174356](https://user-images.githubusercontent.com/59830376/159155157-59ca7357-ab6d-44a5-a57f-0b09018b05d2.png)

I'ts a little problem because I always compare the time code on the DPS page and the time code in the Info page to know if is the same parse or is it a cheat. (In this particular case I assume the guy is not a cheater.)

Could you do something for that please ?

Thank you by advance.

**Comment by Solinur** [comment]
Yes, I'll figure something out. Thanks for bringing this to my attention

**Comment by Solinur** [comment]
This wook me way too long, but it will be fixed in the next version (which will still take a few days)
