### ISSUE TITLE
Arcanist Ability not being counted

### ISSUE THREAD

**Issue by brdalert** [Solinur/CombatMetrics#15]
The arcanist ability fulminating rune does not show as being used in cmx. if I light attack and then use fulminating rune back and forth cmx only show my light attacks and not fulminating rune. so this has been giving me an LAR of grater than 1 in the cmx window

**Comment by Solinur** [comment]
Thanks for reporting this. Somthing must have changed between PTS and Live that affects the tracking. I'll look into it.

**Comment by Solinur** [comment]
Hmm, it seems to work fine for me. Can you confirm that you have Libcombat at version 69 (Its indicated by "LC 69" written in the bottom right of the Main CMX window)

**Comment by Solinur** [comment]
Nervermind. I found the actual issue.

**Comment by Solinur** [comment]
Fixed in v70

**Comment by brdalert** [comment]
thanks for fixing that so quickly
