### ISSUE TITLE
Giving an unique ID ?

### ISSUE THREAD

**Issue by Karnak19** [Solinur/CombatMetrics#2]
Hey Solinur, I love the job you do on CombatMetrics, surely the best add-on in the game !

I'm wondering if you can add an unique ID for each fight datas ?

**Comment by Solinur** [comment]
At the moment the timestamp would be the unique ID.
Wouldn't this suffice? Or do you have something different in mind?

**Comment by Karnak19** [comment]
hummm yes it's not that false. 
Actually, if i'm not wrong when I delete my fight `1`, the fight `2` become the fight `1` and so on ?
Wouldn't be better to auto-increment the ID ? Like if I delete my fight `1`, my fight `2` will still be `2`, for his whole life.

I currently have in mind to create a parse-sharing web platform using these SavedVariables, and I don't really know how to handle this ID *issue* while having a clean and not too heavy code ^^

**Comment by Solinur** [comment]
Every fight has a field "date" which actually is a standard unix timestamp (which is converted on display)

**Comment by Karnak19** [comment]
Oh yes I didn't notice the date field, good ! thanks
