### ISSUE TITLE
Supposedly LibStub isn't needed anymore

### ISSUE THREAD

**Issue by Xellon** [Solinur/CombatMetrics#5]
Comment on lib's page

**LibStub was replaced by features in the game and won't be updated anymore!
If you are using an addon which still relies on LibStub, either ask the author to remove it or you just need to live with it.**

**Comment by Solinur** [comment]
For the time beeing, Libstub is still being used by LibFeedback. However I checked and it is possible to use LibFeedback without a Libstub. With this I finally can remove the dependency.
