### ISSUE TITLE
problem with the russian version of the game

### ISSUE THREAD

**Issue by kawsoft** [Solinur/CombatMetrics#6]
If the game interface is in Russian, your addon does not show anything in the windows except a black background

I looked and found a problem in the file ru.lua
you need to comment out two lines and register new ones or replace

It was:
-- Fonts

SafeAddString(SI_COMBAT_METRICS_STD_FONT, GetString(MEDIUM_FONT), 1) 
SafeAddString(SI_COMBAT_METRICS_BOLD_FONT, GetString(BOLD_FONT), 1)

and need so:
-- Fonts

SafeAddString(SI_COMBAT_METRICS_STD_FONT, "EsoUI/Common/Fonts/Univers57.otf", 1) 
SafeAddString(SI_COMBAT_METRICS_BOLD_FONT, "EsoUI/Common/Fonts/Univers67.otf", 1)

--SafeAddString(SI_COMBAT_METRICS_STD_FONT, GetString(MEDIUM_FONT), 1) 
--SafeAddString(SI_COMBAT_METRICS_BOLD_FONT, GetString(BOLD_FONT), 1)

**Comment by Solinur** [comment]
Thanks for the reply. I thought I corrected this. I'll make sure to really fix it this time.

**Comment by Solinur** [comment]
```
SafeAddString(SI_COMBAT_METRICS_STD_FONT, "$(MEDIUM_FONT)", 1)
SafeAddString(SI_COMBAT_METRICS_BOLD_FONT, "$(BOLD_FONT)", 1)
```
should work. I'll test this.

**Comment by kawsoft** [comment]
yes, work!

**Comment by Solinur** [comment]
Thx, I will upload it this evening :)
