### ISSUE TITLE
How to hide or modify the yellow chat log after parsing?

### ISSUE THREAD

**Issue by nguyenph88** [Solinur/CombatMetrics#8]
Hello,

Hope all is well. This is not an issue but rather a question/concern. Just wondering, how can we hide or modify this yellow text after parsing? I would like to add more details to it to tailor to my needs, and sometimes i just don't want to show it. I tried to disable the chat log but that line is still existing. Hope you could help! Thank you.

![Yellow Text](https://i.imgur.com/wPk419S.png)

**Comment by Solinur** [comment]
This is a feature of the base game and has nothing to do with Combat Metrics.
That doesn't mean it can't be changed, but my take on this is to have the Live Monitor to show you the most important details during or after the fight.

**Comment by nguyenph88** [comment]
Thank you for your reply. I will look more into it then. Really appreciate your time.
